### ISSUE TITLE
Stop after 999 epoch - get image from tensor

### ISSUE THREAD

**Issue by GrzegorzWarzecha** [chu-data-lab/GOGGLES#1]
Hi, Xu really great research!
Do you have any suggestions on why training stops on 999 epoch?

- packages from requirements, 
- rtx 2080ti,
- I tried on different devices, the same on V100, 

Thank you!

![image](https://user-images.githubusercontent.com/5064124/56854184-ea32f480-6932-11e9-955f-bca9a8f37999.png)

![image](https://user-images.githubusercontent.com/5064124/56854222-54e43000-6933-11e9-80ef-7b4a40ee1cf3.png)

**Comment by raininthesun** [comment]
Hi Grzegorz. Thank you for your interest. Sorry for the late reply. We are actively restructuring the code, and hopefully the new code base will be easier to use. Please let us know any issues when you try out the new codebase.
